apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alon-app
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      app.kubernetes.io/name: alon-app
      app.kubernetes.io/instance: alon-app
  endpoints:
    - port: web
      path: /metrics
      interval: 15s

