image:
  repository: 843170960179.dkr.ecr.eu-central-1.amazonaws.com/devops-alon-app
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000
  portName: web

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 6

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 6

